Repository demesameneshoa/recipes-app, pull requests merged in 2023-12, with the labels that each got.

#16 Issue #15 🎫: Models and Junction tables.
  Gemfile
  Gemfile.lock
  app/controllers/foods_controller.rb
  app/controllers/recipes_controller.rb
  app/helpers/foods_helper.rb
  app/helpers/recipes_helper.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/user.rb
  app/views/foods/_food.html.erb
  app/views/foods/_food.json.jbuilder
  app/views/foods/_form.html.erb
  app/views/foods/edit.html.erb
  app/views/foods/index.html.erb
  app/views/foods/index.json.jbuilder
  app/views/foods/new.html.erb
  app/views/foods/show.html.erb
  app/views/foods/show.json.jbuilder
  app/views/recipes/_form.html.erb
  app/views/recipes/_recipe.html.erb
  app/views/recipes/_recipe.json.jbuilder
  app/views/recipes/edit.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/index.json.jbuilder
  app/views/recipes/new.html.erb
  app/views/recipes/show.html.erb
  app/views/recipes/show.json.jbuilder
  config/database.yml
  config/routes.rb
  db/migrate/20231218222718_devise_create_users.rb
  db/migrate/20231218223416_create_recipes.rb
  db/migrate/20231218224014_create_foods.rb
  db/migrate/20231218224428_create_recipe_foods.rb
  db/schema.rb
  spec/factories/foods.rb
  spec/factories/recipes.rb
  spec/factories/users.rb
  spec/helpers/foods_helper_spec.rb
  spec/helpers/recipes_helper_spec.rb
  spec/models/food_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
  spec/requests/foods_spec.rb
  spec/requests/recipes_spec.rb
  spec/routing/foods_routing_spec.rb
  spec/routing/recipes_routing_spec.rb
  spec/views/foods/edit.html.erb_spec.rb
  spec/views/foods/index.html.erb_spec.rb
  spec/views/foods/new.html.erb_spec.rb
  spec/views/foods/show.html.erb_spec.rb
  spec/views/recipes/edit.html.erb_spec.rb
  spec/views/recipes/index.html.erb_spec.rb
  spec/views/recipes/new.html.erb_spec.rb
  spec/views/recipes/show.html.erb_spec.rb
Labels: enhancement

#18 Issue #5 🎫: Login page
  app/views/devise/sessions/new.html.erb
Labels: enhancement, UI

#19 Issue #13 🎫: Food list and form
  app/controllers/foods_controller.rb
  app/models/food.rb
  app/views/foods/_food.html.erb
  app/views/foods/_form.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/layouts/application.html.erb
  spec/factories/foods.rb
  spec/factories/users.rb
  spec/models/food_spec.rb
  spec/views/foods/index.html.erb_spec.rb
Labels: enhancement, Tests, UI

#21 Recipes list Issue #7 🎫
  app/controllers/recipes_controller.rb
  app/models/recipe.rb
  app/views/foods/_form.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/recipes/_form.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  spec/controllers/recipes_controller_spec.rb
  spec/factories/recipes.rb
  spec/models/recipe_spec.rb
  spec/views/recipes/index.html.erb_spec.rb
Labels: enhancement, Tests, UI

#22 Issue #6 🎫: Public recipes
  app/controllers/recipes_controller.rb
  app/models/recipe_food.rb
  app/views/layouts/_navbar.html.erb
  app/views/recipes/public_index.html.erb
  config/routes.rb
  spec/views/recipes/public_index.html.erb_spec.rb
Labels: enhancement, Tests, UI

#24 Issue #12 🎫: General Shopping List (Shopping List)
  app/controllers/shopping_lists_controller.rb
  app/views/layouts/_navbar.html.erb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/show.html.erb
  config/routes.rb
  spec/controllers/shopping_lists_controller_spec.rb
  spec/views/shopping_lists/show.html.erb_spec.rb
Labels: enhancement, Tests, UI

#25 Issue #14 🎫 Final touches
  LICENSE.md
  README.md
  app/controllers/foods_controller.rb
  app/controllers/recipe_foods_controller.rb
  app/controllers/recipes_controller.rb
  app/views/foods/_form.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/recipes/_recipe.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/show.html.erb
  spec/controllers/foods_controller_spec.rb
  spec/examples.txt
  spec/helpers/foods_helper_spec.rb
  spec/helpers/recipes_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/foods_spec.rb
  spec/requests/recipes_spec.rb
  spec/views/foods/edit.html.erb_spec.rb
  spec/views/foods/new.html.erb_spec.rb
  spec/views/foods/show.html.erb_spec.rb
  spec/views/recipes/edit.html.erb_spec.rb
  spec/views/recipes/index.html.erb_spec.rb
  spec/views/recipes/new.html.erb_spec.rb
  spec/views/recipes/public_index.html.erb_spec.rb
  spec/views/recipes/show.html.erb_spec.rb
Labels: documentation, enhancement, Tests, UI
